# Используем официальный образ OpenJDK 17
FROM openjdk:17-slim

# Устанавливаем переменную окружения GREETING
ENV GREETING=Welcome

# Указываем временную папку для контейнера
VOLUME /tmp

# Копируем JAR файл Spring Boot в контейнер
COPY target/untitled-1.0-SNAPSHOT.jar app.jar

# Открываем порт 8080
EXPOSE 8080

# Запускаем приложение
ENTRYPOINT ["java", "-jar", "app.jar"]
